name: Trigger Manual Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Node.js Config
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      
      - name: Yarn Install
        run: npm install -g yarn@1.22.22

      - name: Install dependecies
        run: yarn

      - name: Run unity tests
        run: yarn test

  job2:
    needs: build
    runs-on: ubuntu-latest  

    steps:
      - name: Log
        run: echo "Este workflow foi acionado manualmente!"
